name: 'Deploy Search Index'
description: 'Deploy Hugo Search Index to MeiliSearch Instance'
icon: box
color: red
inputs:
  key:  # id of input
    description: 'MeiliSearch Private API Key'
    required: true
    default: ''
  host:  # id of input
    description: 'MeiliSearch Host Address'
    required: true
    default: ''
  indexName:  # id of input
    description: 'Search Index Name'
    required: true
    default: 'posts'
runs:
  using: 'node12'
  main: 'index.js'

